//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GerToEng
    {
        public int id { get; set; }
        public string german { get; set; }
        public string english { get; set; }
    }
}
